### ISSUE TITLE
Page Content Verification

### ISSUE THREAD

**Issue by georgepsarakis** [georgepsarakis/pitch#7]
Create page checksum from content (optionally by omitting some elements?) and check against a given checksum.

**Comment by georgepsarakis** [comment]
Add PageChecksum plugin to core plugins for direct comparison.

```yaml
- plugin: page_checksum
  remove_tags: ['script', 'style']
  md5: aaaaaaffffffffffffffffffffff
```
